### PR TITLE
Use GitHub Actions to build documentation

### PR DESCRIPTION
**Pull request by georgemccabe**
I added files so that GitHub Actions will run on pull requests and push events for specific branches to build documentation and create warnings log file if any warnings in the documentation occurred. There are currently no warnings in the documentation, but if there were, an artifact called documentation_warnings will be generated in GitHub Actions to easily check if warnings occurred.

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

I verified that GitHub Actions ran successfully and generated an artifact containing the documentation HTML files.

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

* Review the file changes
* Review the log output from the GitHub Actions run
https://github.com/dtcenter/METdatadb/actions/runs/709384478
* Review the content of the documentation artifact (found at the bottom of the summary page for the workflow run)

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [X] After submitting the PR, select **Linked Issues** with the original issue number. - no GitHub issue was created for this task
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by venitahagerty** [comment]
Looks good to me. My only question would be, does it really need Python 3.7 to run? I know I started with Python 3.7, though not using the latest features. Tatiana said it is important to be able to run in Python 3.6 for EMC. I've tested the main code both ways.

**Comment by georgemccabe** [comment]
> 
> 
> Looks good to me. My only question would be, does it really need Python 3.7 to run? I know I started with Python 3.7, though not using the latest features. Tatiana said it is important to be able to run in Python 3.6 for EMC. I've tested the main code both ways.

The documentation is built using Python 3.6 right now.

```
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
```

You can set up GitHub Actions to build with multiple version of Python, so if it is desired we could modify this to build the docs using both 3.6 and 3.7.

**Comment by venitahagerty** [comment]
If you've run it both ways, that works for me.

**Comment by georgemccabe** [comment]
> 
> 
> If you've run it both ways, that works for me.

I have not built the docs using Python 3.7, only 3.6.

**Comment by venitahagerty** [comment]
Looks like you're using Python 3.7 for METdatadb and 3.6 for METplus.

**Pull request merged**
