### PR TITLE
Bugfix sonarqube from METplus-Internal Issue 41

### PR DESCRIPTION
**Pull request by venitahagerty**
## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
Ran the standard large test data, as well as a couple of other small data sets.
- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
I'll run some more tests. If you could test any unusual data, and any uses of read_load_xml.py outside of METdbload.
- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.
- [ ] 
Linked to [Issue 41 from METplus-Internal](https://github.com/dtcenter/METplus-Internal/issues/41)

### CODE REVIEW

**Review by bikegeek — APPROVED** [review]
I ran the METreformat test, which uses read_load_xml on some point stat data and the tests pass.  I will leave the db review portion to someone else.

**Review by TatianaBurek — COMMENTED** [review]
Run full METviewer data load test. Got this error:
Traceback (most recent call last):
  File "/d3/projects/METViewer/METdataio//METdbLoad/ush/met_db_load.py", line 396, in <module>
    main()
  File "/d3/projects/METViewer/METdataio//METdbLoad/ush/met_db_load.py", line 177, in main
    file_data.read_data(xml_loadfile.flags,
  File "/d3/projects/METViewer/METdataio/METdbLoad/ush/read_data_files.py", line 598, in read_data
    all_stat['1'] = all_stat['1'].astype(float)
  File "/d3/projects/METViewer/METviewer_py3.10.4/lib/python3.10/site-packages/pandas/core/generic.py", line 6240, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/d3/projects/METViewer/METviewer_py3.10.4/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 445, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/d3/projects/METViewer/METviewer_py3.10.4/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 347, in apply
    applied = getattr(b, f)(**kwargs)
  File "/d3/projects/METViewer/METviewer_py3.10.4/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 526, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/d3/projects/METViewer/METviewer_py3.10.4/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 299, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/d3/projects/METViewer/METviewer_py3.10.4/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 230, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/d3/projects/METViewer/METviewer_py3.10.4/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 170, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'NA'
Process finished with exit code 1

**Comment by venitahagerty** [comment]
Ran test data that Tatiana sent to me. Replicated bug that she found. There was a problem with an 'NA' in a column. Fixed that problem.

**Review by hankenstein2 — APPROVED** [review]
The changes look good

**Comment by venitahagerty** [comment]
Fixed the time calculation bug that Tatiana found, and then fixed the bug that I accidentally introduced while fixing that bug. I think it's good to go.

**Comment by venitahagerty** [comment]
This Pull Request will also resolve METplus-Internal Issue 45 (in addition to 41), adding the user id to the log output at beginning and end.

**Comment by venitahagerty** [comment]
This Pull Request will also resolve METdataio issues 199 and 202.

**Pull request merged**
