### PR TITLE
Bugfix 247 readnc no lon

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
    read in the sa_test.nc file via METdataio/METreadnc/util/read_netcdf.py

       -  tested on 'cheyenne' and Mac OS
       -  no additional packages needed 
       -  package versions on 'cheyenne':
            -  xarray = 2023.6.0
            -  netcdf4 = 1.6.5
            -  numpy = 1.26.0
            -  h5netcdf = 1.3.0 <- may not need this
      -  package versions on Mac OS
            -  xarray = 2023.1.0
            -  netcdf4 = 1.6.2
            -  numpy = 1.24.2
            -  h5netcdf =  not installed

        Ran pytests under the METdataio/METreadnc/test directory 

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
     - verify that data is correctly read in
     - verify that the instructions in the User's Guide are correct

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[Earliest convenience]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by CPKalb** [comment]
Should I wait for the changes regarding lists or review the pr now?

**Comment by bikegeek** [comment]
I have to add some user's documentation, and was hoping to have a PR ready
by Monday, but I was unavailable on Friday.  You can verify the correctness
of the code.  I had to modify the script so it requires a YAML config file
at the command line and added some pytests.   Let me know if you have any
issues with the refactored code.
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
DTC/Research Applications Lab
Phone: 303-497-8423

*My work hours may not be your work hours. Please do not feel obliged to
reply to this email outside of your normal working hours.*
---------------

**Comment by bikegeek** [comment]
@CPKalb and @fisherhucar, the PR is finally ready again.  All unit tests should now be passing in the Github workflow and the documentation has been completed.

**Review by CPKalb — APPROVED** [review]
I tested the RMM, both OMI, and ENSO use cases, and all produces the same results as with the older version of METdataio.  It is also working for my new stratosphere code.

**Pull request merged**
