### PR TITLE
Renamed .yaml files to be .yml

### PR DESCRIPTION
**Pull request by mollybsmith-noaa**
Pull request to change all .yaml files in METdataio to use .yml, ensuring uniformity.

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
- [ ] Have verified that METdbload still works but I don't really have the capacity to test METreadnc or METreformat

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
- [ ] If possible, test that METreadnc and METreformat are working as expected.

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? -- Change to text of documentation, but no change to documentation structure itself.

- [ ] Do these changes include sufficient testing updates? Yes -- Some test files have extensions changed from .yaml to .yml. If tests pass this should be fine.

- [ ] Will this PR result in changes to the test suite? Yes, see above.

- [ ] Do these changes introduce new SonarQube findings? No</br>
If **yes**, please describe:

- [ ] Please complete this pull request review by **5/3/2024**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by hankenstein2 — APPROVED** [review]
All looks good and all tests have passed

**Comment by jprestop** [comment]
@mollybsmith-noaa and @fisherhucar There was some discussion of this topic in Slack on .yml vs. .yaml.  Minna and I thought the files were to be renamed .yaml and not .yml.  Please see the discussion in the METplus Analysis channel.  I'll go tag you both there now.

**Comment by jprestop** [comment]
Actually, I see that @mollybsmith-noaa added some comments, which I hadn't seen previously.  It sounds like we're waiting to hear back from others before deciding on anything.

**Review by hankenstein2 — COMMENTED** [review]
Ha! Oops, I read this backwards, lets chat in the meeting. I have not merged anything yet.

**Comment by jprestop** [comment]
@fisherhucar No worries.  I won't be at the meeting due to LEAD training, but I'm sure you all have will cover it well.  I'll check in on the notes to see what I missed.

**Pull request closed without merging**
