### PR TITLE
318: update tests/data for MTD 3d cluster

### LINKED ISSUE #318: Create additional tests to METdataio to increase code coverage
To be assigned to John Sharples once he has accepted the invitation to join this repository.

## Describe the Task ##
METdataio, specifically the METdbLoad modules require additional tests to increase the code coverage from its current status.  Add appropriate tests, with particular focus on database loading.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METdataio-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METdataio-X.Y.Z** version, select the **METdataio-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METdataio-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by John-Sharples**
- adds some more test coverage for MTD data

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Tests run locally

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
None
- [x Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [x] Do these changes include sufficient testing updates? **[Yes or No]**
yes
- [x] Will this PR result in changes to the test suite? **[Yes or No]**</br>
yes, increase to 83% coverage

- [ ] Do these changes introduce new SonarQube findings? **[Yes or No]**</br>
If **yes**, please describe:

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **METdataio-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by georgemccabe — CHANGES_REQUESTED** [review]
These changes look good.

I noticed many of the GitHub Actions checks failed, so I reran them and they succeeded.

I checked the SonarQube report and it looks like it is [reporting only 40.7% code coverage](https://needham.rap.ucar.edu/component_measures?id=METdataio&metric=coverage&branch=refs%2Fpull%2F334%2Fmerge&view=list). The code coverage run in GHA [shows 68% coverage](https://github.com/dtcenter/METdataio/actions/runs/10893146979/job/30259153321#step:9:35). I thought you were closer to 80%? Could you check on this and see what is going on? Perhaps some files are being excluded/included in the report when they should not be? The list of files to ignore in SonarQube can be found in the [sonar-project.properties](https://github.com/dtcenter/METdataio/blob/d71479384a431789f54ad0d00db934cc13c24d75/internal/scripts/sonarqube/sonar-project.properties#L7) file.

**Comment by John-Sharples** [comment]
@georgemccabe  I've added some coverage and pytest config in a new pyproject.toml file, this allows us to run a single `pytest` from the top dir. After some trial and error I realise sonarQube has a separate coverage configuration! I've made these consistent and both are now reporting 81%

Please let me know if you're happy with the exclusions, in particular `METdbLoad/sql`. It contains some helper scripts, which are not currently covered by tests, but nor is it application code.

**Review by georgemccabe — APPROVED** [review]
Thanks for making those edits. I see that both the GHA code coverage report and SonarQube both show 81% coverage.

Regarding the exclusion of `METdbLoad/sql`, I am not familiar enough with METdbLoad to know if these scripts should be ignored or not. @bikegeek or @mollybsmith-noaa, do either of you know if these scripts are used elsewhere, e.g. by METviewer or METexpress? If so, we may want to include them in the tests.

**Comment by bikegeek** [comment]
The code under the METdbLoad/sql are all sql "scripts" used to update the
db schema and for loading the schema prior to loading data into a
database.  I believe we can safely exclude the METdbLoad/sql from the GHA
coverage and SonarQube scans.

**Comment by mollybsmith-noaa** [comment]
I just looked myself and fully concur with Minna!

**Pull request merged**
