### PR TITLE
Feature 121 met reformatter

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
**on host 'mohawk', using metdataio_py38 conda environment** 

-  ran tests in METdataio/METreformat/test
-  reformatted the sample ensemble point_stat output from 
 /d2/projects/ens_design_RRFS/sample_point_stat_data for ensemble members1-9:

- created reformatted sample for ensemble members 3 and 7 and used that as input to the METplotpy (develop branch) line plot.
        - no longer seeing the missing stat_xyz column errors
        - running with event_equalization turned on correctly eliminates all data
           for the criteria specified in the custom.yaml config file:           

[custom_line.yaml.txt](https://github.com/dtcenter/METdataio/files/9975306/custom_line.yaml.txt)

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

 _**Recommend running unit tests and generating reformatted data on 'mohawk', where data resides**_

**Run unit tests**

Run in bash shell

Use/create a conda environment that has the following:
    pytest
    pyyaml
    lxml
    pandas 1.2.3
    numpy 1.22
    xarray

on 'seneca' use linux_metplotpy_py38 conda environment:
 conda activate /d1/personal/mwin/miniconda3/envs/linux_metplotpy_py38

on 'mohawk' use metdataio_py38
   conda activate /home/minnawin/miniconda3/envs/metdataio_py38
   
   
Run unit tests in METdataio/METreformat/test
   set PYTHONPATH: 

    export PYTHONPATH=/path/to/METdataio:/path/to/METdatio/METdbLoad:/path/to/METdataio/METdbLoad/ush:/path/to/METdataio/METreformat
   
replace /path/to to the path where METdataio source code is saved

Run the tests from the command line:

     cd /path/to/METdataio/METreformat/test

     pytest

   You shouldn't see any errors/failed tests.

**Reformat sample data**:

There are two "configuration" files:

1) point_stat.xml 
   This is used by the METdataio/METdbLoad reader to read in the .stat files.
   Indicate this in the <folder_tmpl> </folder_tmpl> element. 
   Note: This does NOT work on hierarchical directories, you MUST indicate the full file path to the data:
   /d2/projects/ens_design_RRFS/sample_point_stat_data/mem3/metprd/point_stat_cmn

   Unfortunately this *DOES NOT WORK*:
   projects/ens_design_RRFS/sample_point_stat_data/mem3/metprod
   
   or 
   projects/ens_design_RRFS/sample_point_stat_data/

2) point_stat.yml 
   -  This is used to indicate the full path to the point_stat.xml file is located.
   -  Indicate the path to the directory where you wish to save the output file 
   -  Indicate the name of the output file

a) modify the point_stat.xml file to point to the mem7 directory:

    <folder_tmpl>/d2/projects/ens_design_RRFS/sample_point_stat_data/mem7/metprd/point_stat_cmn</folder_tmpl>

b) modify the point_stat.yaml file to define the output directory and output filename:

    output_dir: /d2/personal/mwin/METdataio/METreformat/output
output_filename: point_stat_mem7.txt
xml_spec_file: /d2/personal/mwin/METdataio/METreformat/point_stat.xml

c) Create  the reformatted data in the mem7/metprd/point_stat_cmn directory:

    python write_stat_ascii.py point_stat.yaml

This single file contains all the reformatted mem7 data. You can view the output in 
a text editor and verify that there are 6 new stat_xyz columns (stat_name, stat_value,
stat_ncl, sta_ncu, stat_bcl, and stat_bcu)

Repeat steps a,b, and c above replacing mem7 references in the point_stat.xml and point_stat.yaml files with mem6 where appropriate.

cd to the output directory and concatenate the mem6 and mem7 files into one (with only one header):

    cat point_stat_mem6.txt < (tail +2 point_stat_mem7.txt) > point_stat_mem6_7.data

**Generate a line plot** 

_**Recommend working on host 'seneca'**_

remote copy the reformatted data from 'mohawk' (point_stat_mem6_7.data) to the METplotpy/metplotpy/plots/line directory on 'seneca'

clone the METplotpy and METcalcpy repositories, and checkout the 'develop' branch

set the PYTHONPATH:

      /_path/to_/METcalcpy:/_path/to_/METcalcpy/metcalcpy:/_path/to_/METplotpy:/_path/to_/METplotpy/metplotpy:/_path/to_/METplotpy/metplotpy/plots

replace /path/to with the path to the METcalcpy and METplotpy source code

**use the metplotpy.v5 conda environment**

    conda activate /home/met_test/.conda/envs/metplotpy.v5

Copy this YAML config file to your METplotpy/metplotpy/plots/line directory as custom.yaml:
   
[custom_line.yaml.txt](https://github.com/dtcenter/METdataio/files/9975457/custom_line.yaml.txt)

Open the custom_line.yaml file and make sure the 
   stat_input: 
   setting is pointing to the reformatted data you scp'd (remote copied) from 'mohawk':

        stat_input: ./point_stat_mem6_7.data

and update the plot_filename (output plot):
 
       plot_filename: ./mem6_7.png

Generate the line plot from the command line:
   
    python line.py custom.yaml

The plotting code should run without errors but will produce event equalization warnings.  However, the stat_xyz files that the plotting code is looking for are now present.  

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[Yes ]**</br>
No new output.  New tests for new functionality.  Each line type reformatting is checked for "correctness".

- [x] Please complete this pull request review by **[As soon as possible]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by willmayfield** [comment]
@bikegeek I cloned this PR on mohawk and loaded your python miniconda environment metdataio_py38. I ran the pytests which passed. I then set up the point_stat.xml and point_stat.yaml files as you described and was able to create a tab-delimited file at /d2/personal/wmayfield/METdataio/METreformat/output. This is identical in size to the one you created, however the groupings, I think by fcst_lead?, seem to be in different orders between the two files. Is there a reason this might be able to happen? (Not that it's a problem if all the same lines are in there)

These lines were output when running the reformatter:

```
WARNING:root:!!! ALPHA line_type has ALPHA value of NA:
 51      VCNT
145     VCNT
239     VCNT
333     VCNT
432     VCNT
531     VCNT
630     VCNT
724     VCNT
818     VCNT
912     VCNT
1006    VCNT
1105    VCNT
1199    VCNT
1293    VCNT
1392    VCNT
1491    VCNT
1585    VCNT
1684    VCNT
1778    VCNT
1877    VCNT
1971    VCNT
2065    VCNT
2159    VCNT
2253    VCNT
Name: line_type, dtype: object
```


I also got metplotpy to plot some lines from the point_stat_mem6_7.data.txt you created. METplotpy was cloned from develop on Cheyenne and using my own python environment.

I started with the yaml file you posted in the PR (the one here: https://github.com/dtcenter/METdataio/files/9975457/custom_line.yaml.txt)

After setting the correct model names and paths for input/output files, I got some messages that resulted in no plot being created at all. The messages led me to vaguely know what part of the plot was causing the problem. These were the issues (other than the DtypeWarning(fixed when I removed a duplicated header line in the middle of the file) and the event equalize warnings):

1. "variance requires at least two data points"
Thinking this must be related to the CIs, I set all of the "std" lines for the CIs to "none" to remove them.
Is this just because there were not always numerical values in the stat_bcl and stat_bcu columns? (there are often either blank tabs or 'NA' when they were not calculated) Maybe, but I'm not sure.

2. "Derived curve can't be calculated. Multiple values for one valid date/fcst_lead"
So, I removed the derived curve, and commented out one line each from the series related-settings (colors, series_symbols, etc.) to match that there is now only four lines.

Looking through the data file, I could never find an example of a RH MAE line that was not unique up to the model and fcst_lead, so the multiple values message is still a mystery to me. It creates lines, so why can't it make the diff of them?  

3. Then there was a warning about not being able to place the vertical line at "18", but when I did try it with some different indy_vals, including 18, that went away.

Here's one of the plots I got:


I think any other plotting issues I had were simply due to not understanding the metplotpy yaml options. 

As far as I can tell the reformatter is placing stat_name and stat_value correctly, but I have a concern about how it is getting the stat_ncl stat_ncu stat_bcl stat_bcu values. It is very hard to confirm that different lines of CNT had consistent use of NA, numerical values, blanks, etc. in the original point_stat output files. Maybe it is bringing over some of that to the reformatted file?
Screen Shot 2022-11-09 at 11 30 47 PM
Thinking the presence of values (they are there for ME and not for MAE) affects whether "std" or "none" can be used for the CIs, I tried:
```
plot_ci:                                                                                                                                                 
- none                                                                                                                                                    
- none                                                                                                                                                    
- std                                                                                                                                                   
- std  
```
This resulted in the same error message as before about the variance and no plot being created.

Then tried:
```
plot_ci:                                                                                                                                                 
- std                                                                                                                                                    
- std                                                                                                                                                    
- none                                                                                                                                                   
- none  
```
This created the plot and had no error message! But, its appearance was the same as the image I put above, i.e. no CIs show up anywhere. I suppose these results are expected, and come from either blank tabs or 'NA' being in the place of stat_bcl and stat_bcu.

**Comment by bikegeek** [comment]
@willmayfield  The Warnings about the VCNT and ALPHA line types are coming from the METdbLoad module that reads in the MET .stat file.  I think the database has issues with alpha line types that are NA, but the METplotpy code does not explicitly look at alpha line types.  

Some of these errors look like they are emanating from the line plot and not necessarily from the input data.  I'll create some additional tests to verify that the bootstrapped values are correctly getting captured (but these are done with pandas, so I suspect things should be correct).

**Comment by bikegeek** [comment]
@willmayfield I managed to get some lines to show up, using the ensemble mem6 and 7 reformatted data I regenerated after consistently handling empty confidence levels:
mem6_7

I got the confidence limit by setting the **plot_ci** setting to **met_prm** (checks for the normal confidence limits because the MAE and ME stats only have the NCU/NCL available)

I wasn't able to use event equalization, and I wasn't able to get the DIFF derived series curve either.  

Here's the line plot config file I used:
[custom_line.yaml.txt](https://github.com/dtcenter/METdataio/files/9992717/custom_line.yaml.txt)

**Review by hankenstein2 — APPROVED** [review]
Ran through all tests on seneca. Ran pytest successfully, ran the write_stat_ascii.py successfully and was able to generate the line plot. Looks great, well done Minna!

**Pull request merged**
