### PR TITLE
Updates to version numbers, dates, rotation of authorship for coordin…

### LINKED ISSUE #357: Create the METdataio v3.0.0 release
*Replace italics below with details for this issue.*

## Describe the Task ##
follow the METplus Release Guide for creating a coordinated release for METdataio.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METdataio-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METdataio-X.Y.Z** version, select the **METdataio-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METdataio-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
…ated release.

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Do these changes introduce new SonarQube findings? **[Yes or No]**</br>
If **yes**, please describe:

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **METdataio-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — CHANGES_REQUESTED** [review]
@bikegeek for the official release, under [Update Release Notes](https://metplus.readthedocs.io/en/develop/Release_Guide/metdataio_official.html#update-release-notes) the instructions say "When creating the official release, combine the beta release sections into one section (i.e. “Version X.Y.Z release notes (YYYYMMDD)”)." so I believe we want to combine all of the betas and rc release notes into one section for the official release so that it has the main header for the page ("METdataio Release Notes") but only one subsection ("METdataio Version 3.0.0 Release Notes (20241217)") but contains all of the dropdowns with the current information that is currently separated into subsections.  Please let me know if you have any questions.

**Comment by bikegeek** [comment]
Thanks!

**Review by jprestop — CHANGES_REQUESTED** [review]
Thanks for making the updates to the release notes, @bikegeek.  I have one more suggestion - instead of leaving the area under "New Functionality" empty, could you please add "NONE" so that users can be sure to know that we didn't add any new functionality instead of inadvertently leaving it blank?  Apologies - I know this is very nit-picky...  One more question - in the upgrade instructions, I noticed that there are references to files with filenames that contain references to "beta" (for example, "METdataio/METdbLoad/sql/updates/update_for_6_0_beta6.sql") and in that [directory](https://github.com/dtcenter/METdataio/tree/main_v3.0/METdbLoad/sql/updates), I see that we previously had filenames like  "[update_for_5_1.sql](https://github.com/dtcenter/METdataio/blob/main_v3.0/METdbLoad/sql/updates/update_for_5_1.sql)".  Do we want to combine the [update_for_6_0_beta4.sql](https://github.com/dtcenter/METdataio/blob/main_v3.0/METdbLoad/sql/updates/update_for_6_0_beta4.sql), [update_for_6_0_beta5.sql](https://github.com/dtcenter/METdataio/blob/main_v3.0/METdbLoad/sql/updates/update_for_6_0_beta5.sql), and [update_for_6_0_beta6.sql](https://github.com/dtcenter/METdataio/blob/main_v3.0/METdbLoad/sql/updates/update_for_6_0_beta6.sql) files into one update_for_6_0.sql file?  I don't fully know what these are or how they are used so I don't know what's best, but thought it was worth inquiring about.

**Comment by bikegeek** [comment]
Thanks Julie.  We DO NOT want to consolidate the mysql files, these are
used for incrementally updating the schemas so they are not documentation
but considered code.

**Review by jprestop — APPROVED** [review]
@bikegeek Thanks for letting me know that we DO NOT want to consolidate the mysql files.  I'm glad you know what's going on!  I went ahead and added "None" under "New Functionality".  I hope that is ok with you. Thank you for all of your work on these releases! I approve this PR.

**Comment by jprestop** [comment]
Ugh, I just noticed it says this is a "Draft".  I went ahead and approved.  Let me know if you need me to re-approve.  Apologies that I did not notice that sooner.

**Pull request merged**
