### PR TITLE
Feature 238 headers

### LINKED ISSUE #238: Documentation: Make Headers Consistent in All METdataio Guides
This is a sub-issue of METplus#*898*.
https://github.com/dtcenter/METplus/issues/898

This task is for all METplus component. This specific issue is for METdataio only:

The headers for the METdataio components User's Guides may not be consistent, but we want them to be.

Here is the syntax from the RST docs (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections):

\# with overline, for parts (e.g. the RTD documentation for the component (i.e. docs/index.rst), each guide (e.g. User's Guide, Contributor's Guide) (i.e. docs/Users_Guide/index.rst, docs/Contributors_Guide/index.rst))
\* with overline, for chapters
=, for sections
-, for subsections
^, for subsubsections
", for paragraphs

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Funding Source ###
2783543 - Lisa has hours on this account.

### Assignee ###
- [x] Select **engineer(s)**  Lisa Goodrich
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

### PR DESCRIPTION
**Pull request by lisagoodrich**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br> 
-  I have reviewed all of the User's Guide files including the index.rst files and updated to the correct header formatting.
-  I also capitalized some of the headers to match formatting across the documentation.
-  I compared the [develop web pages](https://metdataio.readthedocs.io/en/develop/Users_Guide/index.html) to the [feature_238_headers web pages](https://metdataio.readthedocs.io/en/feature_238_headers/Users_Guide/index.html#) all of the headers are in the correct position.  The index and Chapters 1-6 were reviewed.

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br> Please review for any inconsistencies or details that I might have missed.  Were there any other documentation sections?

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No, there are no errors]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [X] Please complete this pull request review by **10/27/23**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — APPROVED** [review]
@lisagoodrich I reviewed all of the User's Guide files both in the "Files Changed" area of this PR and in RTD.  Thanks for those additional capitalization fixes and for all of your work on this task.  I have ensured that all tests passed.  I approve this PR.

**Comment by jprestop** [comment]
@lisagoodrich Please merge the pull request, delete your branch, and close the sub-task issue when you can.

**Comment by lisagoodrich** [comment]
@jprestop  I do not have permission to merge in the changes on this branch.  Is this something @bikegeek could do?

**Comment by jprestop** [comment]
It's ok @lisagoodrich.  I can take care of it.

**Pull request merged**
