### PR TITLE
Feature #289 develop sonarqube_gha

### LINKED ISSUE #289: Add GitHub action to run SonarQube for METdataio pull requests and feature branches
## Describe the New Feature ##
This issue is to add a new SonarQube workflow to GitHub actions to automate the static code analysis for all pull requests. In addition, add a manual trigger workflow dispatch option where the reference branch can be manually specified.

Recommend adding this workflow to both the `develop` branch and the current `main_v*`so that the workflow dispatch option can be made available.

Recommend pushing results to a new SonarQube project named `METdataio GHA` at needham.rap.ucar.edu.

Recommend having the workflow report bad status if the number of SonarQube findings are increased relative to the SonarQube reference.

See issue dtcenter/MET#2379 and its two linked PR's as an example, but the implementation for a python-only repo should be more straight-forward.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Needed for the Air Force - 2771024

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

The following SonarQube issues are closely related:
- [x] dtcenter/METplus#2537
- [x] dtcenter/MET#2379
- [x] dtcenter/METviewer#521
- [x] dtcenter/METplotpy#429
- [x] dtcenter/METcalcpy#366
- [x] dtcenter/METdataio#289

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
These PR adds SonarQube Scanning to GitHub actions, as described below:
1. `sonarqube.yml` defines the new workflow that is triggered by pushes to the develop or main branches, as well as pull requests to those branches. I also added a manual workflow dispatch option, but that won't show up in GitHub until these changes are also made in the `main_v2.1` branch. This workflow checks out the code, determines the current branch name, runs a script to set up the SonarQube properties file, and then calls custom actions to perform the scan and check the results.
2. `configure_sonarqube.sh` customizes the `sonar-project.properties` settings for the current run.
3. `sonar-project.properties` is updated with template values to be updated by `configure_sonarqube.sh` and the `run_sonarqube.sh` script used by the nightly build. 
4. `run_sonarqube.sh` is the script run during the nightly build. This is updated to handle the newly-parameterized `sonar-project.properties` file.
5. Update the PR template to remind PR reviewers to check the SonarQube status.
6. Delete the `internal_tests` directory since the SonarQube scanning files were moved from there to `internal/scripts/sonarqube` (prior to this feature branch) for consistency with other METplus repos.

Note that the scans were enhanced to include the actual code version number rather than just a hard-code string of `1.0`.

Please also see [this issue](https://github.com/dtcenter/METdataio/issues/289#issuecomment-2036205502) comment about a runtime exception. While this exception occurs when running on seneca, it DOES NOT occur when running through GitHub actions. I inspected the log from [this run](https://github.com/dtcenter/METdataio/actions/runs/8556336590/job/23445899038) and see on lines 118-121 that no exception occurs:
```
INFO: Sensor JavaScript inside YAML analysis [javascript] (done) | time=6ms
INFO: Sensor CSS Rules [javascript]
INFO: 1 source file to be analyzed
INFO: 1/1 source file has been analyzed
```

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
I manually ran the SonarQube scan for both the `develop` and `main_v2.1` branches so that they'd present in needham.rap.ucar.edu to serve as references.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
- Review the code changes.
- Confirm that the SonarQube workflow runs for this PR.
- Inspect the SonarQube server:
  - For GitHub actions: https://needham.rap.ucar.edu/dashboard?id=METdataio-GHA
  - For Nightly build: https://needham.rap.ucar.edu/dashboard?id=METdataio_NB

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
None needed.

- [x] Do these changes include sufficient testing updates? **[Yes]**
None needed.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[Fri 4/5/24]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [x] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by JohnHalleyGotway** [comment]
@bikegeek and @jprestop, I'm moving this PR from draft to being ready for review. I think I've tied up all the loose ends. I'll submit a similar PR for the `main_v2.1` branch to get these changes into the default branch... and then move on to the other METplus repos.

**Comment by bikegeek** [comment]
I can take a look at it, should we try to get this into the beta4 release?

**Comment by JohnHalleyGotway** [comment]
@bikegeek, yes, since it came together so quickly and easily, I think I'll try to get all of these changes in for beta4. Working on the companion PR for the main_v2.1 branch now.

**Comment by bikegeek** [comment]
I will add METreformat to the list of sonar.sources in the sonar-project-properties.  There are some tests for the METreformat code, so the code coverage **should** be >0% if the tests are getting picked up.

**Review by bikegeek — APPROVED** [review]
I added METreformat to the sonar_project.properties.  All the expected behaviors are observed.  Approving.

**Pull request merged**
