### PR TITLE
318: Get existing tests working

### PR DESCRIPTION
**Pull request by John-Sharples**
In this PR:
 - Added functionality to `conftest.py` to write some test files to a temp directory
 - Use temp files to run tests in `test/`
 - Tests can now be run with `pytest test/`
 - `METdbLoad/test/test_tables.py` wrapped in a function and marked to skip.

Not in the PR
 - An assessment of whether the current tests do anything useful
 - The tests in `tests/` (plural) still error during setup

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Run locally

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please check these changes run wherever we expect this code to work

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
Extensive comments in code.

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
tests now use temp files and can be run anywhere.

- [x] Do these changes introduce new SonarQube findings? **[Yes or No]**</br>
If **yes**, please describe:
Not sure.

- [x] Please complete this pull request review by **[Fill in date]**.</br>
No rush.

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **METdataio-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by bikegeek — APPROVED** [review]
Tested on RAL internal host with database and MET data, running the tests modified in this PR.

**Comment by bikegeek** [comment]
I will let you do the Squash and merge, and delete the branch.

**Comment by John-Sharples** [comment]
@bikegeek It appears I'm not authorised to merge this PR

**Comment by bikegeek** [comment]
You have 'write' privileges to this repository, I'll see what other things
need to be set for you to perform merges.  In the meantime, I've performed
the squash and merge.

Regards,
Minna

**Pull request merged**
