### PR TITLE
Feature 213 db load instructions

### LINKED ISSUE #213: Add documentation for loading data into a database
Create instructions in the User's Guide on the data base steps necessary for loading MET output into a METviewer database.  Use the instructions provided by Julie Prestopnik that contains instructions for dropping, creating, and setting up permissions for database.

## Describe the Task ##
*Provide a description of the task here.*

### Time Estimate ###
~1 day
### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
   Verified scripts and configuration files work on 'mohawk'
   

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

  **Verify that formatting and instructions are correct in the documentation:**
 
    https://metdataio.readthedocs.io/en/feature_213_db_load_instructions/Users_Guide/load_data.html#

   **Used this YAML config file for 'mohawk' and data in /scratch/mwin (remove the .txt extension before using)**

[mohawk_data_loading_config.yaml.txt](https://github.com/dtcenter/METdataio/files/12149039/mohawk_data_loading_config.yaml.txt)

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes ]**

- [x] Do these changes include sufficient testing updates? **[NA]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **Before coordinated release**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
@bikegeek I added a Status and Cycle under "Projects" and also linked with the issue under "Development".  I will start reviewing soon.

**Comment by jprestop** [comment]
@bikegeek 
I am following this part of the instructions:
```
Generate the new XML specification file by running the following:

cd path-to-METdataio-source/METdataio/METdbLoad/sql/scripts

*Replace path-to-METdataio-source to the location where the METdataio source code is saved.

python generate_xml_spec.py path-to/data_loading_config.yaml

*Replace the path-to with the path to the directory you created to store the copy of the data_loading_config.yaml
file as specified earlier.
```

When I run into an error:
```
mohawk:jpresto:/d2/personal/jpresto/METdataio/git/METdataio-feature_213_db_load_instructions/METdataio/METdbLoad/sql/scripts> python generate_xml_spec.py /d2/personal/jpresto/METdataio/pr_214/mohawk_data_loading_config.yaml
  File "generate_xml_spec.py", line 22
    db_name: str
           ^
SyntaxError: invalid syntax
```

I realized that Python was pointing to Python 2:
```
mohawk:jpresto:/d2/personal/jpresto/METdataio/git/METdataio-feature_213_db_load_instructions/METdataio/METdbLoad/sql/scripts> python --version
Python 2.7.16
```
so I tried running with Python 3, but then I get a different error:
```
mohawk:jpresto:/d2/personal/jpresto/METdataio/git/METdataio-feature_213_db_load_instructions/METdataio/METdbLoad/sql/scripts> python3 generate_xml_spec.py /d2/personal/jpresto/METdataio/pr_214/mohawk_data_loading_config.yaml
Traceback (most recent call last):
  File "generate_xml_spec.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
Can you please send the path to the version of Python you used on mohawk for testing?  Thanks!

**Comment by bikegeek** [comment]
Here is the yaml env file:

name: metdataio_310
channels:
  - defaults
dependencies:
  - python=3.10
  - mamba
  - lxml=4.9.1
  - numpy=1.24.2
  - pandas=1.5.2
  - pip=22.2.2
  - pymysql=1.0.2
  - pytest=7.2.1
  - python-dateutil=2.8.2
  - pyyaml=6.0
  - ca-certificates
  - certifi
  - openssl

**Comment by jprestop** [comment]
Thanks @bikegeek.  What version of Python did you use on mohawk for testing?

**Comment by jprestop** [comment]
Actually, I don't mean to ask what version, but rather can you please send the path to the Python that you used?

**Comment by bikegeek** [comment]
Python 3.10
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by bikegeek** [comment]
/d2/personal/mwin/miniconda3/envs/metdataio_310/bin/python
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
Thanks @bikegeek, the path is just what I needed!

When running this part of the instructions:
```
python met_db_load.py /path-to/load_met.xml

* Replace the path-to with the location where the load_met.xml file was saved.  This is the same directory
  you created to save the copy of the data_loading_config.yaml file.
```

I get an error:
```
mohawk:jpresto:/d2/personal/jpresto/METdataio/git/METdataio-feature_213_db_load_instructions/METdataio/METdbLoad/ush> **/d2/personal/mwin/miniconda3/envs/metdataio_310/bin/python met_db_load.py /d2/personal/jpresto/METdataio/pr_214/load_met.xml** 
INFO:root:METdbload Version: __version__ = "2.1.0-rc1"
INFO:root:--- *** --- Start METdbLoad --- *** ---
INFO:root:Begin time: 2023-07-25 16:45:25.212910
INFO:root:User name is: jpresto
INFO:root:Reading XML Load file
INFO:root:Database name is: mv_test
INFO:root:Initial number of files: 144
DEBUG:root:[--- Start read_data ---]
DEBUG:root:Lines in /scratch/mwin/grid_stat_000000L_20220206_053500V.stat: 50
... (more DEBUG messages here)
DEBUG:root:Shape of all_stat before transforms: (4244, 129)
DEBUG:root:Shape of all_stat after transforms: (4244, 131)
INFO:root:    >>> Read time: 0:00:02.063934
DEBUG:root:[--- End read_data ---]
ERROR:root:*** (1049, "Unknown database 'mv_test'") in run_sql ***
*** Error when connecting to database
```
I'm not sure what I need to do - apologies.

**Comment by bikegeek** [comment]
my apologies, I cleaned up the database, I re-created it and loaded the schema.

**Review by jprestop — APPROVED** [review]
@bikegeek, I verified that the formatting and instructions are correct in the [documentation](https://metdataio.readthedocs.io/en/feature_213_db_load_instructions/Users_Guide/load_data.html#) to the best of my knowledge.  As someone who as very little knowledge of this work, the instructions were easy to follow.  Thank you.

I am wondering if it would be helpful to have the error I received:
```
ERROR:root:*** (1049, "Unknown database 'mv_test'") in run_sql ***
*** Error when connecting to database
```
in the [Troubleshooting section](https://metdataio.readthedocs.io/en/feature_213_db_load_instructions/Users_Guide/load_data.html#troubleshooting)?   I defer to your judgement on that, as you will know best.  In either case, I approve this request.  Thank you for all of your work in putting all of this together!  I think it will be very helpful!

**Comment by bikegeek** [comment]
Thanks for the suggestion, I added that error to the troubleshooting table.  I kept the original format of the table, as all attempts to modify the table to make Error and Solution into separate columns made the text difficult to read:
https://metdataio.readthedocs.io/en/feature_213_db_load_instructions/Users_Guide/load_data.html#load-data

**Comment by jprestop** [comment]
@bikegeek I think it looks great!

**Pull request merged**
